recommendation: change filter banner from a notification
RocketCommunicationsInc/ttc-monitor-react pull request #53
Opened 2023-07-12 15:31 UTC by kiley-mitti

There's not really an official recommendation here, and Notification Banner may well be the way to go here, but I made a small stylistic change here to make the filter notification fall more inline with the way rux-log does it. Absolutely feel free to deny this.

2023-07-12 17:49 UTC, kiley-mitti commented on src/Components/Alerts/Alerts.tsx
> +      <div className="filter-notification" hidden={!dataFiltered}>
Into it! One moment and I'll get that in.

2023-07-12 17:55 UTC, kiley-mitti commented on src/Components/Alerts/Alerts.tsx
> +      <div className="filter-notification" hidden={!dataFiltered}>
That'll. show up next build :) thanks for the idea! :)

2023-07-12 18:32 UTC, FMorrison87 requested changes

2023-07-12 18:32 UTC, FMorrison87 commented on src/Components/Alerts/Alerts.css
> +    box-shadow: none;
Can you add in padding-inline: var(--spacing-1) so it doesn't have so much space between the text?

2023-07-12 19:26 UTC, kiley-mitti commented on src/Components/Alerts/Alerts.css
> +    box-shadow: none;
sure thing! will be in the next deploy preview

2023-07-12 21:41 UTC, NicDominguez reviewed
I think we should get a design decision on this before merging as we use rux-notification for many tables in dashboard and this pattern would change those as well. @kiley-mitti will you check in with design about making this change?

2023-07-13 13:18 UTC, FMorrison87 commented on src/Components/Alerts/Alerts.css
> +    box-shadow: none;
*Chef's kiss*

2023-07-13 14:21 UTC, kiley-mitti commented
I'm on it! Be back soon with more info. :)

2023-07-13 15:44 UTC, kiley-mitti commented
@NicDominguez I asked in AstroInternal and the main consensus seems to be that we don't have a strong pattern for announcing filtering but the simpler display is preferred to distinguish it from Notification Banner.

2023-07-13 20:12 UTC, Paterma approved these changes

2023-07-13 20:28 UTC, NicDominguez approved these changes

2023-07-13 20:45 UTC, merged